services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8081
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/feedpulse
      - GEMINI_API_KEY=AIzaSyDUvb1pUj4wYcGg_y8DpR8Q-2XoJn1YqXU
      - JWT_SECRET=feedpulse_secret_key_2026
      - ADMIN_EMAIL=admin@feedpulse.com
      - ADMIN_PASSWORD=admin123
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
